In [21]:
import os
os.environ["PYARROW_IGNORE_TIMEZONE"] = "1"

import pyspark.pandas as pd
from pyspark.sql import SparkSession

In [22]:
builder = SparkSession.builder.appName('app')
builder = builder.config('spark.sql.execution.arrow.pyspark.enabled','true') 
builder.getOrCreate()

In [23]:
# read file

df_rh = pd.read_parquet('data/2024-11-04_temp.parquet', index_col='matricula')

In [24]:
df_rh.head(3)

           empresa_codigo  estabelecimento_codigo                    estabelecimento_nome  centro_de_resultado_codigo             centro_de_resultado_nome                  nome         cpf data_de_nascimento estado_civil_nome deficiente deficiencia  idade       sexo raca_cor             nome_1                    e_mail         email_alternativo           pis data_da_admissao  situacao_do_empregado  funcao_codigo        funcao_nome  cargo_codigo         cargo_nome vinculo_empregaticio_nome salario_tipo prazo_de_contrato nro_de_horas  empresa_codigo_1  chefia_imediata_cod_estab  chefia_imediata_matricula             chefia_imediata_nome         funcao_nome_1                e_mail_1  codigo  categoria_profissional_cod     categoria_profissional_nome                                razao_social                    nome_2  tipo_de_vaga dt_extracao
matricula
6                       3                       3  ASSOC PARAN CULTURA-PUC PR CAMPUS CTBA                        3541  ADMINISTRACAO DA GRADUACAO EM MEDIC       NELSON TREVISAN     9121900         04/03/1934            Casado        Não        None     90  Masculino   Branca          Doutorado  nelson.trevisan@pucpr.br  nelson.trevisan@pucpr.br  1003883555-7       01/03/1959  Demissão - 06/07/2018         501238  PROFESSOR TITULAR          5648  PROFESSOR TITULAR                   Docente            H     Indeterminado       100,00               3.0                        3.0                    27887.0               ROBSON IVAN STIVAL  PROFESSOR ASSISTENTE  robson.stival@pucpr.br       1                           1  PROFESSORES DO ENSINO SUPERIOR  SIND DOS PROFESSORES DO ENSINO SUPERIOR PR  Dispensa sem Justa Causa             1  2024-11-04
35                      3                       3  ASSOC PARAN CULTURA-PUC PR CAMPUS CTBA                        3541  ADMINISTRACAO DA GRADUACAO EM MEDIC  SERGIO FONSECA TARLE     8044953         06/09/1938          Solteiro        Não        None     86  Masculino   Branca      Pós Graduação     sergio.tarle@pucpr.br                      None  1022325191-4       01/08/1967  Demissão - 06/10/2016         101197  PROFESSOR ADJUNTO          2197  PROFESSOR ADJUNTO                   Docente            H     Indeterminado       100,00               3.0                        3.0                    22797.0  KELLY CHRISTINE LANDOLFI BETTIO     PROFESSOR ADJUNTO   kelly.bettio@pucpr.br       1                           1  PROFESSORES DO ENSINO SUPERIOR  SIND DOS PROFESSORES DO ENSINO SUPERIOR PR                     Morte             1  2024-11-04
43                      3                       3  ASSOC PARAN CULTURA-PUC PR CAMPUS CTBA                        3498  ADMINISTRACAO DA GRADUACAO EM BIOLO          RUBENS VIANA  1048082920         19/11/1934            Casado        Não        None     89  Masculino   Branca  Educação Superior     rubens.viana@pucpr.br     rubens.viana@pucpr.br  1023336836-9       01/03/1968  Demissão - 08/08/2017         101251  PROFESSOR TITULAR          2251  PROFESSOR TITULAR                   Docente            H     Indeterminado       100,00               3.0                        3.0                    22797.0  KELLY CHRISTINE LANDOLFI BETTIO     PROFESSOR ADJUNTO   kelly.bettio@pucpr.br       1                           1  PROFESSORES DO ENSINO SUPERIOR  SIND DOS PROFESSORES DO ENSINO SUPERIOR PR  Dispensa sem Justa Causa             1  2024-11-04

Exibindo plano de execucao

In [26]:
df_rh.describe()

       empresa_codigo  estabelecimento_codigo  centro_de_resultado_codigo           cpf         idade  funcao_codigo   cargo_codigo  empresa_codigo_1  chefia_imediata_cod_estab  chefia_imediata_matricula        codigo  categoria_profissional_cod  tipo_de_vaga
count         16265.0            16265.000000                1.626500e+04  1.626500e+04  16265.000000   16265.000000   16265.000000      11013.000000               16244.000000               1.624400e+04  16265.000000                16265.000000  16265.000000
mean              3.0                7.540301                1.460795e+05  1.916314e+10     39.586105  416064.953151    4860.545712          9.677835                   7.427727               4.740111e+07      2.513065                   10.285029      1.029942
std               0.0                8.260477                2.197737e+05  2.589466e+10     11.840948  164497.160929    5838.544591         81.373965                   9.162713               4.492936e+07      2.017714                   10.052600      0.170431
min               3.0                1.000000                1.000000e+00  7.349000e+05     15.000000      67.000000    1007.000000          1.000000                   1.000000               6.000000e+00      1.000000                    1.000000      1.000000
25%               3.0                2.000000                1.020180e+05  4.390307e+09     31.000000  500123.000000    5076.000000          3.000000                   2.000000               2.482200e+04      1.000000                    3.000000      1.000000
50%               3.0                3.000000                1.035190e+05  7.726082e+09     38.000000  501048.000000    5637.000000          3.000000                   3.000000               9.000157e+07      1.000000                    3.000000      1.000000
75%               3.0               11.000000                1.230140e+05  1.387649e+10     46.000000  501237.000000    5716.000000          3.000000                  11.000000               9.000491e+07      5.000000                   21.000000      1.000000
max               3.0               38.000000                1.032686e+06  9.990025e+10     92.000000  512311.000000  512264.000000        999.000000                  82.000000               9.001195e+07     17.000000                   56.000000      2.000000

In [28]:
df_rh.spark.explain(mode='formatted')

== Physical Plan ==
* Project (3)
+- * ColumnarToRow (2)
   +- Scan parquet  (1)


(1) Scan parquet
Output [42]: [empresa_codigo#1581L, estabelecimento_codigo#1582L, estabelecimento_nome#1583, centro_de_resultado_codigo#1584L, centro_de_resultado_nome#1585, matricula#1586L, nome#1587, cpf#1588L, data_de_nascimento#1589, estado_civil_nome#1590, deficiente#1591, deficiencia#1592, idade#1593L, sexo#1594, raca_cor#1595, nome_1#1596, e_mail#1597, email_alternativo#1598, pis#1599, data_da_admissao#1600, situacao_do_empregado#1601, funcao_codigo#1602L, funcao_nome#1603, cargo_codigo#1604L, cargo_nome#1605, vinculo_empregaticio_nome#1606, salario_tipo#1607, prazo_de_contrato#1608, nro_de_horas#1609, empresa_codigo_1#1610, chefia_imediata_cod_estab#1611, chefia_imediata_matricula#1612, chefia_imediata_nome#1613, funcao_nome_1#1614, e_mail_1#1615, codigo#1616L, categoria_profissional_cod#1617L, categoria_profissional_nome#1618, razao_social#1619, nome_2#1620, tipo_de_vaga#1621L, dt_extracao#1622]
Batched: true
Location: InMemoryFileIndex [file:/home/jovyan/data/2024-11-04_temp.parquet]
ReadSchema: struct<empresa_codigo:bigint,estabelecimento_codigo:bigint,estabelecimento_nome:string,centro_de_resultado_codigo:bigint,centro_de_resultado_nome:string,matricula:bigint,nome:string,cpf:bigint,data_de_nascimento:string,estado_civil_nome:string,deficiente:string,deficiencia:string,idade:bigint,sexo:string,raca_cor:string,nome_1:string,e_mail:string,email_alternativo:string,pis:string,data_da_admissao:string,situacao_do_empregado:string,funcao_codigo:bigint,funcao_nome:string,cargo_codigo:bigint,cargo_nome:string,vinculo_empregaticio_nome:string,salario_tipo:string,prazo_de_contrato:string,nro_de_horas:string,empresa_codigo_1:double,chefia_imediata_cod_estab:double,chefia_imediata_matricula:double,chefia_imediata_nome:string,funcao_nome_1:string,e_mail_1:string,codigo:bigint,categoria_profissional_cod:bigint,categoria_profissional_nome:string,razao_social:string,nome_2:string,tipo_de_vaga:bigint,dt_extracao:string>

(2) ColumnarToRow [codegen id : 1]
Input [42]: [empresa_codigo#1581L, estabelecimento_codigo#1582L, estabelecimento_nome#1583, centro_de_resultado_codigo#1584L, centro_de_resultado_nome#1585, matricula#1586L, nome#1587, cpf#1588L, data_de_nascimento#1589, estado_civil_nome#1590, deficiente#1591, deficiencia#1592, idade#1593L, sexo#1594, raca_cor#1595, nome_1#1596, e_mail#1597, email_alternativo#1598, pis#1599, data_da_admissao#1600, situacao_do_empregado#1601, funcao_codigo#1602L, funcao_nome#1603, cargo_codigo#1604L, cargo_nome#1605, vinculo_empregaticio_nome#1606, salario_tipo#1607, prazo_de_contrato#1608, nro_de_horas#1609, empresa_codigo_1#1610, chefia_imediata_cod_estab#1611, chefia_imediata_matricula#1612, chefia_imediata_nome#1613, funcao_nome_1#1614, e_mail_1#1615, codigo#1616L, categoria_profissional_cod#1617L, categoria_profissional_nome#1618, razao_social#1619, nome_2#1620, tipo_de_vaga#1621L, dt_extracao#1622]

(3) Project [codegen id : 1]
Output [42]: [matricula#1586L, empresa_codigo#1581L, estabelecimento_codigo#1582L, estabelecimento_nome#1583, centro_de_resultado_codigo#1584L, centro_de_resultado_nome#1585, nome#1587, cpf#1588L, data_de_nascimento#1589, estado_civil_nome#1590, deficiente#1591, deficiencia#1592, idade#1593L, sexo#1594, raca_cor#1595, nome_1#1596, e_mail#1597, email_alternativo#1598, pis#1599, data_da_admissao#1600, situacao_do_empregado#1601, funcao_codigo#1602L, funcao_nome#1603, cargo_codigo#1604L, cargo_nome#1605, vinculo_empregaticio_nome#1606, salario_tipo#1607, prazo_de_contrato#1608, nro_de_horas#1609, empresa_codigo_1#1610, chefia_imediata_cod_estab#1611, chefia_imediata_matricula#1612, chefia_imediata_nome#1613, funcao_nome_1#1614, e_mail_1#1615, codigo#1616L, categoria_profissional_cod#1617L, categoria_profissional_nome#1618, razao_social#1619, nome_2#1620, tipo_de_vaga#1621L, dt_extracao#1622]
Input [42]: [empresa_codigo#1581L, estabelecimento_codigo#1582L, estabelecimento_nome#1583, centro_de_resultado_codigo#1584L, centro_de_resultado_nome#1585, matricula#1586L, nome#1587, cpf#1588L, data_de_nascimento#1589, estado_civil_nome#1590, deficiente#1591, deficiencia#1592, idade#1593L, sexo#1594, raca_cor#1595, nome_1#1596, e_mail#1597, email_alternativo#1598, pis#1599, data_da_admissao#1600, situacao_do_empregado#1601, funcao_codigo#1602L, funcao_nome#1603, cargo_codigo#1604L, cargo_nome#1605, vinculo_empregaticio_nome#1606, salario_tipo#1607, prazo_de_contrato#1608, nro_de_horas#1609, empresa_codigo_1#1610, chefia_imediata_cod_estab#1611, chefia_imediata_matricula#1612, chefia_imediata_nome#1613, funcao_nome_1#1614, e_mail_1#1615, codigo#1616L, categoria_profissional_cod#1617L, categoria_profissional_nome#1618, razao_social#1619, nome_2#1620, tipo_de_vaga#1621L, dt_extracao#1622]